# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 338cf6db97dbca527be6c5dad892e21ef834936099fdabec477f036af9e0dcb102466f0948aa74a6ea528f1174798d928d38f91eec0ebf4d261ce7ef782884b9

test:
  secret_key_base: 892f92e4b015e5e3489cac7232cd85e10bba9bc80b95b15d53a58789bceecf448767661ed90cd0b3ac11f0e9d53f2ccada012185bbeabffbcf8f76be6a30e670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
